services:
  db:
    image: postgres:16-alpine
    container_name: financeiro-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: financeiro
      POSTGRES_PASSWORD: financeiro123
      POSTGRES_DB: financeiro
    ports:
      - "5432:5432"
    volumes:
      - financeiro_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financeiro -d financeiro"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  financeiro_pgdata: